name: CI Test for clingoLP

on: [push]

jobs:
  build-linux:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
          activate-environment: fluto
      # - name: Test clingoLP
      #   run: |
      #     conda init bash
      #     source ~/.bashrc
      #     conda activate clingoLP
      #     python setup.py install
      #     pytest -v ./flutopy/tests/test.py

  build-macos:
    runs-on: "macos-latest"
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
          activate-environment: fluto
      # - name: Test clingoLP
      #   run: |
      #     conda init bash
      #     source /Users/runner/.bash_profile
      #     conda activate clingoLP
      #     python setup.py install
      #     pytest -v ./flutopy/tests/test.py

  build-windows:
    runs-on: "windows-latest"
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
          activate-environment: fluto
      # - name: Test clingoLP
      #   run: |
      #     python setup.py install
      #     pytest -v ./flutopy/tests/test.py
